micronaut:
  application:
    name: rmqVhost
netty:
  default:
    allocator:
      max-order: 3

rabbitmq:
  servers:
    default-server:
      host: 127.0.0.1
      port: 5673
      user: guest
      pass: guest
    custom-server:
      host: 127.0.0.1
      port: 5673
      user: guest
      pass: guest
      virtual-host: custom-virtual-host
